<?php

namespace Database\Seeders;

use App\Models\Card;
use Illuminate\Database\Seeder;

class CardSeeder extends Seeder
{
    public function run(): void
    {
        $cards = [
            // ===== WARRIOR =====
            [
                'name' => 'Iron Golem',
                'description' => 'A towering construct of ancient iron, forged in the fires of the deep forge.',
                'mana_cost' => 6,
                'attack' => 7,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'warrior',
                'flavor_text' => 'Iron never yields.',
            ],
            [
                'name' => 'Blade Whirlwind',
                'description' => 'Deal 2 damage to all minions.',
                'mana_cost' => 2,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'warrior',
                'flavor_text' => 'A storm of steel.',
            ],
            [
                'name' => 'Fortress Knight',
                'description' => 'Taunt. Stands firm against all attackers.',
                'mana_cost' => 3,
                'attack' => 3,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'warrior',
                'flavor_text' => 'None shall pass.',
            ],
            [
                'name' => 'Warlord\'s Axe',
                'description' => 'A massive axe that cleaves through enemy defenses.',
                'mana_cost' => 4,
                'attack' => 5,
                'health' => 3,
                'card_type' => 'weapon',
                'rarity' => 'rare',
                'hero_class' => 'warrior',
                'flavor_text' => 'Victory belongs to the bold.',
            ],
            [
                'name' => 'Battle-Hardened Veteran',
                'description' => 'Whenever this minion takes damage, gain +1 Attack.',
                'mana_cost' => 5,
                'attack' => 4,
                'health' => 6,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'warrior',
                'flavor_text' => 'Scars are just reminders of battles survived.',
            ],
            [
                'name' => 'Rampart Crusher',
                'description' => 'Charge. This minion can attack immediately.',
                'mana_cost' => 7,
                'attack' => 8,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'warrior',
                'flavor_text' => 'No wall stands twice.',
            ],
            [
                'name' => 'Lord of the Iron Keep',
                'description' => 'Battlecry: Give all friendly minions +2/+2.',
                'mana_cost' => 8,
                'attack' => 6,
                'health' => 7,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'warrior',
                'flavor_text' => 'His presence alone turns the tide of battle.',
            ],
            [
                'name' => 'Shield Bearer',
                'description' => 'Taunt. Protect your hero with this stalwart defender.',
                'mana_cost' => 2,
                'attack' => 1,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'warrior',
                'flavor_text' => 'My shield is my creed.',
            ],
            [
                'name' => 'War Stomp',
                'description' => 'Deal 3 damage to an enemy minion.',
                'mana_cost' => 3,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'warrior',
                'flavor_text' => 'Feel the earth tremble.',
            ],
            [
                'name' => 'Ironclad Champion',
                'description' => 'Divine Shield. Once per game, nullifies the first attack.',
                'mana_cost' => 5,
                'attack' => 5,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'warrior',
                'flavor_text' => 'Blessed by the forge-god himself.',
            ],

            // ===== MAGE =====
            [
                'name' => 'Arcane Bolt',
                'description' => 'Deal 3 damage to any target.',
                'mana_cost' => 1,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'mage',
                'flavor_text' => 'Pure arcane energy condensed to a point.',
            ],
            [
                'name' => 'Frost Nova',
                'description' => 'Freeze all enemy minions.',
                'mana_cost' => 3,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'mage',
                'flavor_text' => 'Time itself seems to stop.',
            ],
            [
                'name' => 'Arcane Familiar',
                'description' => 'Whenever you cast a spell, gain +1/+1.',
                'mana_cost' => 1,
                'attack' => 1,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'mage',
                'flavor_text' => 'It feeds on raw magic.',
            ],
            [
                'name' => 'Meteor Strike',
                'description' => 'Deal 15 damage to a minion and 3 damage to adjacent minions.',
                'mana_cost' => 6,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'epic',
                'hero_class' => 'mage',
                'flavor_text' => 'From the void above, destruction rains.',
            ],
            [
                'name' => 'Conjured Scholar',
                'description' => 'Battlecry: Draw a spell from your deck.',
                'mana_cost' => 3,
                'attack' => 2,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'mage',
                'flavor_text' => 'Knowledge is power manifested.',
            ],
            [
                'name' => 'Glacial Wyrm',
                'description' => 'Taunt. Whenever this minion attacks, freeze the target.',
                'mana_cost' => 5,
                'attack' => 3,
                'health' => 7,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'mage',
                'flavor_text' => 'Ancient ice flows through its veins.',
            ],
            [
                'name' => 'Archmagus Vexara',
                'description' => 'Battlecry: Deal 4 damage to all enemies. Summon a 2/2 Arcane Clone for each killed.',
                'mana_cost' => 9,
                'attack' => 5,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'mage',
                'flavor_text' => 'Destructor. Creator. Archmagus.',
            ],
            [
                'name' => 'Fireball',
                'description' => 'Deal 6 damage to any target.',
                'mana_cost' => 4,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'mage',
                'flavor_text' => 'A classic for good reason.',
            ],
            [
                'name' => 'Blink Sprite',
                'description' => 'Charge. 1/1 that strikes first.',
                'mana_cost' => 2,
                'attack' => 1,
                'health' => 1,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'mage',
                'flavor_text' => 'Here, gone, here again.',
            ],
            [
                'name' => 'Arcane Surge',
                'description' => 'Deal 2 damage to all enemies. Draw a card.',
                'mana_cost' => 5,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'mage',
                'flavor_text' => 'Knowledge flows from chaos.',
            ],

            // ===== RANGER =====
            [
                'name' => 'Swift Wolf',
                'description' => 'Charge. Hunts prey from the moment it arrives.',
                'mana_cost' => 2,
                'attack' => 2,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'ranger',
                'flavor_text' => 'The hunt never waits.',
            ],
            [
                'name' => 'Arrow Storm',
                'description' => 'Deal 1 damage to all enemies.',
                'mana_cost' => 5,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'ranger',
                'flavor_text' => 'A shadow of arrows blots out the sun.',
            ],
            [
                'name' => 'Beast Tamer',
                'description' => 'Battlecry: Give a friendly Beast +2/+1.',
                'mana_cost' => 4,
                'attack' => 3,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'ranger',
                'flavor_text' => 'Master of the wild.',
            ],
            [
                'name' => 'Venomous Arrow',
                'description' => 'Deal 2 damage to a minion and poison it.',
                'mana_cost' => 2,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'ranger',
                'flavor_text' => 'A slow but certain death.',
            ],
            [
                'name' => 'Great Stag',
                'description' => 'Rush. A noble beast of the ancient forest.',
                'mana_cost' => 5,
                'attack' => 5,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'ranger',
                'flavor_text' => 'Its antlers have gored a hundred foes.',
            ],
            [
                'name' => 'Trap Layer',
                'description' => 'Secret: When an enemy attacks, deal 4 damage to that minion.',
                'mana_cost' => 3,
                'attack' => 2,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'ranger',
                'flavor_text' => 'Every step in the forest could be your last.',
            ],
            [
                'name' => 'Sylvan Huntress',
                'description' => 'Battlecry: Summon two 2/1 Forest Wolves. Give them Charge.',
                'mana_cost' => 7,
                'attack' => 4,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'ranger',
                'flavor_text' => 'She never hunts alone.',
            ],
            [
                'name' => 'Eagle Eye Shot',
                'description' => 'Deal 3 damage to any target. If you have a Beast, deal 5 instead.',
                'mana_cost' => 3,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'ranger',
                'flavor_text' => 'Precision above all.',
            ],
            [
                'name' => 'Forest Sprite',
                'description' => 'A small but quick creature of the deep woods.',
                'mana_cost' => 1,
                'attack' => 1,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'ranger',
                'flavor_text' => 'Seen only when it wants to be seen.',
            ],
            [
                'name' => 'Razor Boar',
                'description' => 'When this minion attacks, it also deals 1 damage to the opponent\'s hero.',
                'mana_cost' => 4,
                'attack' => 4,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'ranger',
                'flavor_text' => 'Fear the tusks.',
            ],

            // ===== PALADIN =====
            [
                'name' => 'Holy Guardian',
                'description' => 'Divine Shield. The first attack against this minion is negated.',
                'mana_cost' => 4,
                'attack' => 3,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'paladin',
                'flavor_text' => 'Faith manifests as armor.',
            ],
            [
                'name' => 'Sacred Light',
                'description' => 'Restore 6 health to your hero or a friendly minion.',
                'mana_cost' => 2,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'paladin',
                'flavor_text' => 'The light answers all prayers.',
            ],
            [
                'name' => 'Silver Crusader',
                'description' => 'Divine Shield. Taunt. A champion blessed by the light.',
                'mana_cost' => 5,
                'attack' => 5,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'paladin',
                'flavor_text' => 'No evil shall pass.',
            ],
            [
                'name' => 'Consecrated Ground',
                'description' => 'Deal 2 damage to all enemy minions.',
                'mana_cost' => 4,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'paladin',
                'flavor_text' => 'Holy fire purges corruption.',
            ],
            [
                'name' => 'Order\'s Champion',
                'description' => 'Battlecry: Give all friendly minions Divine Shield.',
                'mana_cost' => 7,
                'attack' => 5,
                'health' => 6,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'paladin',
                'flavor_text' => 'She carries the light for all.',
            ],
            [
                'name' => 'Radiant Squire',
                'description' => 'At the end of your turn, gain +1/+1.',
                'mana_cost' => 1,
                'attack' => 1,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'paladin',
                'flavor_text' => 'Small but growing.',
            ],
            [
                'name' => 'High Inquisitor Solara',
                'description' => 'Battlecry: Equip a 4/2 Holy Blade. Destroy any demon it kills.',
                'mana_cost' => 8,
                'attack' => 5,
                'health' => 7,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'paladin',
                'flavor_text' => 'The light\'s judgment is absolute.',
            ],
            [
                'name' => 'Beacon of Hope',
                'description' => 'Restore 3 health to all friendly characters.',
                'mana_cost' => 5,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'paladin',
                'flavor_text' => 'Even in darkness, a light remains.',
            ],
            [
                'name' => 'Templar Knight',
                'description' => 'Charge. Holy and swift.',
                'mana_cost' => 3,
                'attack' => 3,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'paladin',
                'flavor_text' => 'Strike before the darkness spreads.',
            ],
            [
                'name' => 'Hallowed Strike',
                'description' => 'Deal 4 damage to a minion. If it dies, gain 4 health.',
                'mana_cost' => 4,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'epic',
                'hero_class' => 'paladin',
                'flavor_text' => 'Justice returns as vitality.',
            ],

            // ===== DRUID =====
            [
                'name' => 'Ancient Treant',
                'description' => 'Taunt. A guardian of the old forest.',
                'mana_cost' => 5,
                'attack' => 4,
                'health' => 6,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'druid',
                'flavor_text' => 'The forest remembers all transgressions.',
            ],
            [
                'name' => 'Wild Growth',
                'description' => 'Gain an empty Mana Crystal this turn.',
                'mana_cost' => 2,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'druid',
                'flavor_text' => 'Nature does not wait.',
            ],
            [
                'name' => 'Shapeshifter',
                'description' => 'At the start of your turn, transform into a 4/6 with Taunt.',
                'mana_cost' => 3,
                'attack' => 2,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'druid',
                'flavor_text' => 'Bear or cat, it is always deadly.',
            ],
            [
                'name' => 'Thornweaver',
                'description' => 'Battlecry: Add a 2/2 Thornling to your hand.',
                'mana_cost' => 2,
                'attack' => 2,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'druid',
                'flavor_text' => 'From one come many.',
            ],
            [
                'name' => 'Moonfire Blessing',
                'description' => 'Give a friendly minion +2/+2 and Taunt.',
                'mana_cost' => 3,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'druid',
                'flavor_text' => 'The moon\'s silver light strengthens the willing.',
            ],
            [
                'name' => 'Grove Protector',
                'description' => 'Taunt. Whenever you play a spell, gain +1 Health.',
                'mana_cost' => 4,
                'attack' => 3,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'druid',
                'flavor_text' => 'The forest grows around it.',
            ],
            [
                'name' => 'Archdruid Coraven',
                'description' => 'Battlecry: Summon copies of all friendly minions. They cost (0).',
                'mana_cost' => 10,
                'attack' => 5,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'druid',
                'flavor_text' => 'One becomes many. Many becomes a forest.',
            ],
            [
                'name' => 'Nature\'s Wrath',
                'description' => 'Deal 5 damage to all enemies.',
                'mana_cost' => 7,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'epic',
                'hero_class' => 'druid',
                'flavor_text' => 'The earth\'s fury knows no mercy.',
            ],
            [
                'name' => 'Verdant Lurker',
                'description' => 'Stealth. Strikes unseen from the undergrowth.',
                'mana_cost' => 2,
                'attack' => 2,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'druid',
                'flavor_text' => 'Still as moss, quick as lightning.',
            ],
            [
                'name' => 'Overgrowth',
                'description' => 'Gain two empty Mana Crystals.',
                'mana_cost' => 4,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'epic',
                'hero_class' => 'druid',
                'flavor_text' => 'Nature accelerates for those who listen.',
            ],

            // ===== NEUTRAL =====
            [
                'name' => 'Village Peasant',
                'description' => 'A humble farmer thrust into war.',
                'mana_cost' => 1,
                'attack' => 1,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'neutral',
                'flavor_text' => 'Courage needs no armor.',
            ],
            [
                'name' => 'Goblin Tinkerer',
                'description' => 'Battlecry: Give a friendly minion +1 Attack.',
                'mana_cost' => 2,
                'attack' => 2,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'neutral',
                'flavor_text' => 'Every weapon needs tuning.',
            ],
            [
                'name' => 'Stone Elemental',
                'description' => 'Taunt. Unmoving, unyielding.',
                'mana_cost' => 3,
                'attack' => 2,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'neutral',
                'flavor_text' => 'Made of the land itself.',
            ],
            [
                'name' => 'Ogre Brute',
                'description' => 'Battlecry: Deal 2 damage to a random enemy.',
                'mana_cost' => 4,
                'attack' => 5,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'neutral',
                'flavor_text' => 'Aim is overrated.',
            ],
            [
                'name' => 'Swamp Dragon',
                'description' => 'Taunt. A ancient beast from the marshlands.',
                'mana_cost' => 7,
                'attack' => 7,
                'health' => 8,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'neutral',
                'flavor_text' => 'The swamp gives and the swamp takes.',
            ],
            [
                'name' => 'Wandering Hermit',
                'description' => 'Battlecry: Restore 3 health to your hero.',
                'mana_cost' => 3,
                'attack' => 2,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'neutral',
                'flavor_text' => 'Wisdom walked these roads long before armies.',
            ],
            [
                'name' => 'Shadow Wraith',
                'description' => 'Stealth. Deals double damage when attacking from stealth.',
                'mana_cost' => 4,
                'attack' => 3,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'neutral',
                'flavor_text' => 'Darkness given form.',
            ],
            [
                'name' => 'Mercenary Captain',
                'description' => 'All friendly minions cost (1) less.',
                'mana_cost' => 5,
                'attack' => 4,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'neutral',
                'flavor_text' => 'Gold is the universal language.',
            ],
            [
                'name' => 'Ancient Colossus',
                'description' => 'Taunt. Cannot be targeted by spells.',
                'mana_cost' => 8,
                'attack' => 8,
                'health' => 10,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'neutral',
                'flavor_text' => 'Built before memory, it will outlast all memory.',
            ],
            [
                'name' => 'The Realm Watcher',
                'description' => 'Battlecry: Look at the top 3 cards of your deck. Put them back in any order.',
                'mana_cost' => 6,
                'attack' => 6,
                'health' => 6,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'neutral',
                'flavor_text' => 'It sees all, knows all, judges all.',
            ],
        ];

        foreach ($cards as $cardData) {
            Card::updateOrCreate(['name' => $cardData['name']], $cardData);
        }
    }
}
