<?php

namespace Database\Seeders;

use App\Models\Card;
use Illuminate\Database\Seeder;

class CardSeeder extends Seeder
{
    public function run(): void
    {
        $cards = [
            // ===== WARRIOR =====
            [
                'name' => 'Iron Golem',
                'description' => 'A towering construct of ancient iron, forged in the fires of the deep forge.',
                'mana_cost' => 6,
                'attack' => 7,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'warrior',
                'flavor_text' => 'Iron never yields.',
            ],
            [
                'name' => 'Blade Whirlwind',
                'description' => 'Deal 2 damage to all minions.',
                'mana_cost' => 2,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'warrior',
                'flavor_text' => 'A storm of steel.',
            ],
            [
                'name' => 'Fortress Knight',
                'description' => 'Taunt. Stands firm against all attackers.',
                'mana_cost' => 3,
                'attack' => 3,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'warrior',
                'flavor_text' => 'None shall pass.',
            ],
            [
                'name' => 'Warlord\'s Axe',
                'description' => 'A massive axe that cleaves through enemy defenses.',
                'mana_cost' => 4,
                'attack' => 5,
                'health' => 3,
                'card_type' => 'weapon',
                'rarity' => 'rare',
                'hero_class' => 'warrior',
                'flavor_text' => 'Victory belongs to the bold.',
            ],
            [
                'name' => 'Battle-Hardened Veteran',
                'description' => 'Whenever this minion takes damage, gain +1 Attack.',
                'mana_cost' => 5,
                'attack' => 4,
                'health' => 6,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'warrior',
                'flavor_text' => 'Scars are just reminders of battles survived.',
            ],
            [
                'name' => 'Rampart Crusher',
                'description' => 'Charge. This minion can attack immediately.',
                'mana_cost' => 7,
                'attack' => 8,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'warrior',
                'flavor_text' => 'No wall stands twice.',
            ],
            [
                'name' => 'Lord of the Iron Keep',
                'description' => 'Battlecry: Give all friendly minions +2/+2.',
                'mana_cost' => 8,
                'attack' => 6,
                'health' => 7,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'warrior',
                'flavor_text' => 'His presence alone turns the tide of battle.',
            ],
            [
                'name' => 'Shield Bearer',
                'description' => 'Taunt. Protect your hero with this stalwart defender.',
                'mana_cost' => 2,
                'attack' => 1,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'warrior',
                'flavor_text' => 'My shield is my creed.',
            ],
            [
                'name' => 'War Stomp',
                'description' => 'Deal 3 damage to an enemy minion.',
                'mana_cost' => 3,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'warrior',
                'flavor_text' => 'Feel the earth tremble.',
            ],
            [
                'name' => 'Ironclad Champion',
                'description' => 'Divine Shield. Once per game, nullifies the first attack.',
                'mana_cost' => 5,
                'attack' => 5,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'warrior',
                'flavor_text' => 'Blessed by the forge-god himself.',
            ],

            // ===== MAGE =====
            [
                'name' => 'Arcane Bolt',
                'description' => 'Deal 3 damage to any target.',
                'mana_cost' => 1,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'mage',
                'flavor_text' => 'Pure arcane energy condensed to a point.',
            ],
            [
                'name' => 'Frost Nova',
                'description' => 'Freeze all enemy minions.',
                'mana_cost' => 3,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'mage',
                'flavor_text' => 'Time itself seems to stop.',
            ],
            [
                'name' => 'Arcane Familiar',
                'description' => 'Whenever you cast a spell, gain +1/+1.',
                'mana_cost' => 1,
                'attack' => 1,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'mage',
                'flavor_text' => 'It feeds on raw magic.',
            ],
            [
                'name' => 'Meteor Strike',
                'description' => 'Deal 15 damage to a minion and 3 damage to adjacent minions.',
                'mana_cost' => 6,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'epic',
                'hero_class' => 'mage',
                'flavor_text' => 'From the void above, destruction rains.',
            ],
            [
                'name' => 'Conjured Scholar',
                'description' => 'Battlecry: Draw a spell from your deck.',
                'mana_cost' => 3,
                'attack' => 2,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'mage',
                'flavor_text' => 'Knowledge is power manifested.',
            ],
            [
                'name' => 'Glacial Wyrm',
                'description' => 'Taunt. Whenever this minion attacks, freeze the target.',
                'mana_cost' => 5,
                'attack' => 3,
                'health' => 7,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'mage',
                'flavor_text' => 'Ancient ice flows through its veins.',
            ],
            [
                'name' => 'Archmagus Vexara',
                'description' => 'Battlecry: Deal 4 damage to all enemies. Summon a 2/2 Arcane Clone for each killed.',
                'mana_cost' => 9,
                'attack' => 5,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'mage',
                'flavor_text' => 'Destructor. Creator. Archmagus.',
            ],
            [
                'name' => 'Fireball',
                'description' => 'Deal 6 damage to any target.',
                'mana_cost' => 4,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'mage',
                'flavor_text' => 'A classic for good reason.',
            ],
            [
                'name' => 'Blink Sprite',
                'description' => 'Charge. 1/1 that strikes first.',
                'mana_cost' => 2,
                'attack' => 1,
                'health' => 1,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'mage',
                'flavor_text' => 'Here, gone, here again.',
            ],
            [
                'name' => 'Arcane Surge',
                'description' => 'Deal 2 damage to all enemies. Draw a card.',
                'mana_cost' => 5,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'mage',
                'flavor_text' => 'Knowledge flows from chaos.',
            ],

            // ===== RANGER =====
            [
                'name' => 'Swift Wolf',
                'description' => 'Charge. Hunts prey from the moment it arrives.',
                'mana_cost' => 2,
                'attack' => 2,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'ranger',
                'flavor_text' => 'The hunt never waits.',
            ],
            [
                'name' => 'Arrow Storm',
                'description' => 'Deal 1 damage to all enemies.',
                'mana_cost' => 5,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'ranger',
                'flavor_text' => 'A shadow of arrows blots out the sun.',
            ],
            [
                'name' => 'Beast Tamer',
                'description' => 'Battlecry: Give a friendly Beast +2/+1.',
                'mana_cost' => 4,
                'attack' => 3,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'ranger',
                'flavor_text' => 'Master of the wild.',
            ],
            [
                'name' => 'Venomous Arrow',
                'description' => 'Deal 2 damage to a minion and poison it.',
                'mana_cost' => 2,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'ranger',
                'flavor_text' => 'A slow but certain death.',
            ],
            [
                'name' => 'Great Stag',
                'description' => 'Rush. A noble beast of the ancient forest.',
                'mana_cost' => 5,
                'attack' => 5,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'ranger',
                'flavor_text' => 'Its antlers have gored a hundred foes.',
            ],
            [
                'name' => 'Trap Layer',
                'description' => 'Secret: When an enemy attacks, deal 4 damage to that minion.',
                'mana_cost' => 3,
                'attack' => 2,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'ranger',
                'flavor_text' => 'Every step in the forest could be your last.',
            ],
            [
                'name' => 'Sylvan Huntress',
                'description' => 'Battlecry: Summon two 2/1 Forest Wolves. Give them Charge.',
                'mana_cost' => 7,
                'attack' => 4,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'ranger',
                'flavor_text' => 'She never hunts alone.',
            ],
            [
                'name' => 'Eagle Eye Shot',
                'description' => 'Deal 3 damage to any target. If you have a Beast, deal 5 instead.',
                'mana_cost' => 3,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'ranger',
                'flavor_text' => 'Precision above all.',
            ],
            [
                'name' => 'Forest Sprite',
                'description' => 'A small but quick creature of the deep woods.',
                'mana_cost' => 1,
                'attack' => 1,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'ranger',
                'flavor_text' => 'Seen only when it wants to be seen.',
            ],
            [
                'name' => 'Razor Boar',
                'description' => 'When this minion attacks, it also deals 1 damage to the opponent\'s hero.',
                'mana_cost' => 4,
                'attack' => 4,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'ranger',
                'flavor_text' => 'Fear the tusks.',
            ],

            // ===== PALADIN =====
            [
                'name' => 'Holy Guardian',
                'description' => 'Divine Shield. The first attack against this minion is negated.',
                'mana_cost' => 4,
                'attack' => 3,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'paladin',
                'flavor_text' => 'Faith manifests as armor.',
            ],
            [
                'name' => 'Sacred Light',
                'description' => 'Restore 6 health to your hero or a friendly minion.',
                'mana_cost' => 2,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'paladin',
                'flavor_text' => 'The light answers all prayers.',
            ],
            [
                'name' => 'Silver Crusader',
                'description' => 'Divine Shield. Taunt. A champion blessed by the light.',
                'mana_cost' => 5,
                'attack' => 5,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'paladin',
                'flavor_text' => 'No evil shall pass.',
            ],
            [
                'name' => 'Consecrated Ground',
                'description' => 'Deal 2 damage to all enemy minions.',
                'mana_cost' => 4,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'paladin',
                'flavor_text' => 'Holy fire purges corruption.',
            ],
            [
                'name' => 'Order\'s Champion',
                'description' => 'Battlecry: Give all friendly minions Divine Shield.',
                'mana_cost' => 7,
                'attack' => 5,
                'health' => 6,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'paladin',
                'flavor_text' => 'She carries the light for all.',
            ],
            [
                'name' => 'Radiant Squire',
                'description' => 'At the end of your turn, gain +1/+1.',
                'mana_cost' => 1,
                'attack' => 1,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'paladin',
                'flavor_text' => 'Small but growing.',
            ],
            [
                'name' => 'High Inquisitor Solara',
                'description' => 'Battlecry: Equip a 4/2 Holy Blade. Destroy any demon it kills.',
                'mana_cost' => 8,
                'attack' => 5,
                'health' => 7,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'paladin',
                'flavor_text' => 'The light\'s judgment is absolute.',
            ],
            [
                'name' => 'Beacon of Hope',
                'description' => 'Restore 3 health to all friendly characters.',
                'mana_cost' => 5,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'paladin',
                'flavor_text' => 'Even in darkness, a light remains.',
            ],
            [
                'name' => 'Templar Knight',
                'description' => 'Charge. Holy and swift.',
                'mana_cost' => 3,
                'attack' => 3,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'paladin',
                'flavor_text' => 'Strike before the darkness spreads.',
            ],
            [
                'name' => 'Hallowed Strike',
                'description' => 'Deal 4 damage to a minion. If it dies, gain 4 health.',
                'mana_cost' => 4,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'epic',
                'hero_class' => 'paladin',
                'flavor_text' => 'Justice returns as vitality.',
            ],

            // ===== DRUID =====
            [
                'name' => 'Ancient Treant',
                'description' => 'Taunt. A guardian of the old forest.',
                'mana_cost' => 5,
                'attack' => 4,
                'health' => 6,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'druid',
                'flavor_text' => 'The forest remembers all transgressions.',
            ],
            [
                'name' => 'Wild Growth',
                'description' => 'Gain an empty Mana Crystal this turn.',
                'mana_cost' => 2,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'common',
                'hero_class' => 'druid',
                'flavor_text' => 'Nature does not wait.',
            ],
            [
                'name' => 'Shapeshifter',
                'description' => 'At the start of your turn, transform into a 4/6 with Taunt.',
                'mana_cost' => 3,
                'attack' => 2,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'druid',
                'flavor_text' => 'Bear or cat, it is always deadly.',
            ],
            [
                'name' => 'Thornweaver',
                'description' => 'Battlecry: Add a 2/2 Thornling to your hand.',
                'mana_cost' => 2,
                'attack' => 2,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'druid',
                'flavor_text' => 'From one come many.',
            ],
            [
                'name' => 'Moonfire Blessing',
                'description' => 'Give a friendly minion +2/+2 and Taunt.',
                'mana_cost' => 3,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'rare',
                'hero_class' => 'druid',
                'flavor_text' => 'The moon\'s silver light strengthens the willing.',
            ],
            [
                'name' => 'Grove Protector',
                'description' => 'Taunt. Whenever you play a spell, gain +1 Health.',
                'mana_cost' => 4,
                'attack' => 3,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'druid',
                'flavor_text' => 'The forest grows around it.',
            ],
            [
                'name' => 'Archdruid Coraven',
                'description' => 'Battlecry: Summon copies of all friendly minions. They cost (0).',
                'mana_cost' => 10,
                'attack' => 5,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'druid',
                'flavor_text' => 'One becomes many. Many becomes a forest.',
            ],
            [
                'name' => 'Nature\'s Wrath',
                'description' => 'Deal 5 damage to all enemies.',
                'mana_cost' => 7,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'epic',
                'hero_class' => 'druid',
                'flavor_text' => 'The earth\'s fury knows no mercy.',
            ],
            [
                'name' => 'Verdant Lurker',
                'description' => 'Stealth. Strikes unseen from the undergrowth.',
                'mana_cost' => 2,
                'attack' => 2,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'druid',
                'flavor_text' => 'Still as moss, quick as lightning.',
            ],
            [
                'name' => 'Overgrowth',
                'description' => 'Gain two empty Mana Crystals.',
                'mana_cost' => 4,
                'attack' => null,
                'health' => null,
                'card_type' => 'spell',
                'rarity' => 'epic',
                'hero_class' => 'druid',
                'flavor_text' => 'Nature accelerates for those who listen.',
            ],

            // ===== NEUTRAL =====
            [
                'name' => 'Village Peasant',
                'description' => 'A humble farmer thrust into war.',
                'mana_cost' => 1,
                'attack' => 1,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'neutral',
                'flavor_text' => 'Courage needs no armor.',
            ],
            [
                'name' => 'Goblin Tinkerer',
                'description' => 'Battlecry: Give a friendly minion +1 Attack.',
                'mana_cost' => 2,
                'attack' => 2,
                'health' => 2,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'neutral',
                'flavor_text' => 'Every weapon needs tuning.',
            ],
            [
                'name' => 'Stone Elemental',
                'description' => 'Taunt. Unmoving, unyielding.',
                'mana_cost' => 3,
                'attack' => 2,
                'health' => 5,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'neutral',
                'flavor_text' => 'Made of the land itself.',
            ],
            [
                'name' => 'Ogre Brute',
                'description' => 'Battlecry: Deal 2 damage to a random enemy.',
                'mana_cost' => 4,
                'attack' => 5,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'neutral',
                'flavor_text' => 'Aim is overrated.',
            ],
            [
                'name' => 'Swamp Dragon',
                'description' => 'Taunt. A ancient beast from the marshlands.',
                'mana_cost' => 7,
                'attack' => 7,
                'health' => 8,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'neutral',
                'flavor_text' => 'The swamp gives and the swamp takes.',
            ],
            [
                'name' => 'Wandering Hermit',
                'description' => 'Battlecry: Restore 3 health to your hero.',
                'mana_cost' => 3,
                'attack' => 2,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'common',
                'hero_class' => 'neutral',
                'flavor_text' => 'Wisdom walked these roads long before armies.',
            ],
            [
                'name' => 'Shadow Wraith',
                'description' => 'Stealth. Deals double damage when attacking from stealth.',
                'mana_cost' => 4,
                'attack' => 3,
                'health' => 3,
                'card_type' => 'minion',
                'rarity' => 'rare',
                'hero_class' => 'neutral',
                'flavor_text' => 'Darkness given form.',
            ],
            [
                'name' => 'Mercenary Captain',
                'description' => 'All friendly minions cost (1) less.',
                'mana_cost' => 5,
                'attack' => 4,
                'health' => 4,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'neutral',
                'flavor_text' => 'Gold is the universal language.',
            ],
            [
                'name' => 'Ancient Colossus',
                'description' => 'Taunt. Cannot be targeted by spells.',
                'mana_cost' => 8,
                'attack' => 8,
                'health' => 10,
                'card_type' => 'minion',
                'rarity' => 'epic',
                'hero_class' => 'neutral',
                'flavor_text' => 'Built before memory, it will outlast all memory.',
            ],
            [
                'name' => 'The Realm Watcher',
                'description' => 'Battlecry: Look at the top 3 cards of your deck. Put them back in any order.',
                'mana_cost' => 6,
                'attack' => 6,
                'health' => 6,
                'card_type' => 'minion',
                'rarity' => 'legendary',
                'hero_class' => 'neutral',
                'flavor_text' => 'It sees all, knows all, judges all.',
            ],

            // ===== NECROMANCER =====
            ['name' => 'Skeleton Archer',       'description' => 'Battlecry: Deal 1 damage to a minion.',                                            'mana_cost' => 2,  'attack' => 2,    'health' => 1,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'Bone fingers find the mark.'],
            ['name' => 'Rotting Corpse',         'description' => 'At the start of your turn, this minion loses 1 Health.',                           'mana_cost' => 1,  'attack' => 1,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'It just keeps going.'],
            ['name' => 'Bone Hound',             'description' => 'Deathrattle: Summon a 1/1 Bone Fragment.',                                         'mana_cost' => 3,  'attack' => 3,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'Even in death it bites.'],
            ['name' => 'Crypt Warden',           'description' => 'Taunt.',                                                                            'mana_cost' => 2,  'attack' => 1,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'The crypt needs no sleep.'],
            ['name' => 'Gravedigger',            'description' => 'Battlecry: Draw a card if a friendly minion died this turn.',                       'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'Every grave is an opportunity.'],
            ['name' => 'Plague Rat',             'description' => 'Poisonous.',                                                                        'mana_cost' => 1,  'attack' => 1,    'health' => 1,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'One bite is enough.'],
            ['name' => 'Bone Golem',             'description' => 'Gains +1 Attack for each minion that died this game.',                              'mana_cost' => 4,  'attack' => 3,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'Built from the fallen.'],
            ['name' => 'Lichling',               'description' => 'Deathrattle: Return this minion to your hand with +1/+1.',                          'mana_cost' => 3,  'attack' => 2,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'necromancer', 'flavor_text' => 'It remembers every death.'],
            ['name' => 'Soul Reaper',            'description' => 'Battlecry: Destroy a friendly minion to deal 4 damage to an enemy.',                'mana_cost' => 4,  'attack' => 4,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'necromancer', 'flavor_text' => 'Sacrifice is the currency of power.'],
            ['name' => 'Deathbound Revenant',    'description' => 'Whenever a friendly minion dies, gain +1/+0.',                                      'mana_cost' => 5,  'attack' => 4,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'necromancer', 'flavor_text' => 'It feeds on loss.'],
            ['name' => 'Banshee',                'description' => 'Battlecry: Silence an enemy minion.',                                               'mana_cost' => 3,  'attack' => 2,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'necromancer', 'flavor_text' => 'Her wail strips all enchantments.'],
            ['name' => 'Corpse Amalgam',         'description' => 'Has the keywords of your fallen minions this game.',                                'mana_cost' => 6,  'attack' => 5,    'health' => 6,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'necromancer', 'flavor_text' => 'The sum of many sorrows.'],
            ['name' => 'Dread Wraith',           'description' => 'At the end of your turn, deal 1 damage to all enemies.',                            'mana_cost' => 5,  'attack' => 5,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'necromancer', 'flavor_text' => 'Fear is its weapon.'],
            ['name' => 'Void Horror',            'description' => 'Costs 1 less for each minion that died this turn.',                                 'mana_cost' => 6,  'attack' => 6,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'necromancer', 'flavor_text' => 'It arrives when the dying is done.'],
            ['name' => 'Lich Necromancer',       'description' => 'Battlecry: Raise your fallen minions as 2/2 Skeletons.',                            'mana_cost' => 7,  'attack' => 5,    'health' => 7,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'necromancer', 'flavor_text' => 'The dead obey.'],
            ['name' => 'The Undying King',       'description' => 'Deathrattle: Return to life with 3 Health. Once per game.',                         'mana_cost' => 8,  'attack' => 7,    'health' => 7,    'card_type' => 'minion', 'rarity' => 'legendary', 'hero_class' => 'necromancer', 'flavor_text' => 'Death is merely an inconvenience.'],
            ['name' => 'Raise Dead',             'description' => 'Return a friendly minion that died this game to the battlefield.',                   'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'Rise once more.'],
            ['name' => 'Necrotic Bolt',          'description' => 'Deal 2 damage. If the target dies, draw a card.',                                   'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'Corrosion given direction.'],
            ['name' => 'Bone Wall',              'description' => 'Summon three 1/1 Skeleton tokens.',                                                 'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'Quantity has a quality all its own.'],
            ['name' => 'Death Pact',             'description' => 'Destroy a friendly minion to restore 6 Health to your hero.',                       'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'A willing sacrifice.'],
            ['name' => 'Shadow Touch',           'description' => 'Give a minion -2 Attack until end of turn.',                                        'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'Doubt is the greatest poison.'],
            ['name' => 'Death Coil',             'description' => 'Deal 5 damage to a minion. If it dies, summon a 2/2 Zombie.',                       'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'necromancer', 'flavor_text' => 'The process never stops.'],
            ['name' => 'Soul Harvest',           'description' => 'Destroy all minions with 2 or less Health. Restore 2 Health for each.',              'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'necromancer', 'flavor_text' => 'Reap what others have sown.'],
            ['name' => 'Plague Cloud',           'description' => 'Deal 2 damage to all enemy minions.',                                               'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'necromancer', 'flavor_text' => 'It spares no one.'],
            ['name' => 'Army of the Dead',       'description' => 'Summon a 2/2 Skeleton for each minion that died this game.',                        'mana_cost' => 6,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'necromancer', 'flavor_text' => 'An army that never runs out.'],
            ['name' => 'Eternal Darkness',       'description' => 'Silence all enemy minions.',                                                        'mana_cost' => 5,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'necromancer', 'flavor_text' => 'Memories fade. Power remains.'],
            ['name' => "Death's Embrace",        'description' => 'Destroy all minions. For each friendly minion destroyed, summon a 3/3 Undead.',     'mana_cost' => 8,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'legendary', 'hero_class' => 'necromancer', 'flavor_text' => 'In ruin, rebirth.'],
            ['name' => 'Bone Scythe',            'description' => 'Deathrattle: Summon a 2/2 Skeleton.',                                               'mana_cost' => 3,  'attack' => 3,    'health' => 2,    'card_type' => 'weapon', 'rarity' => 'common',    'hero_class' => 'necromancer', 'flavor_text' => 'The harvest never ends.'],
            ['name' => 'Soul Blade',             'description' => 'After attacking a minion, it loses 1 Health at the start of each turn.',             'mana_cost' => 4,  'attack' => 4,    'health' => 2,    'card_type' => 'weapon', 'rarity' => 'rare',      'hero_class' => 'necromancer', 'flavor_text' => 'A wound that festers.'],
            ["name" => "Reaper's Edge",          'description' => 'Overkill: Raise the slain minion as a 3/3 Undead.',                                  'mana_cost' => 5,  'attack' => 4,    'health' => 3,    'card_type' => 'weapon', 'rarity' => 'epic',      'hero_class' => 'necromancer', 'flavor_text' => 'Death is not the end.'],

            // ===== SHAMAN =====
            ['name' => 'Earth Totem',            'description' => 'Taunt.',                                                                             'mana_cost' => 1,  'attack' => 0,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'Rooted to the land.'],
            ['name' => 'Fire Totem',             'description' => 'At end of your turn, deal 1 damage to a random enemy.',                              'mana_cost' => 1,  'attack' => 0,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'Endlessly patient, endlessly burning.'],
            ['name' => 'Storm Caller',           'description' => 'Battlecry: Deal 1 damage to all enemies.',                                           'mana_cost' => 2,  'attack' => 2,    'health' => 1,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'Calls the storm to heel.'],
            ['name' => 'Mud Lurker',             'description' => 'Taunt. Battlecry: Gain +1/+0 if you control an Earth Totem.',                       'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'The mud hides many things.'],
            ['name' => 'Lava Sprite',            'description' => 'Rush.',                                                                              'mana_cost' => 3,  'attack' => 3,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'Born from the deep magma.'],
            ['name' => 'Wind Walker',            'description' => 'Rush. Windfury.',                                                                    'mana_cost' => 2,  'attack' => 1,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'Twice as fast. Twice as dangerous.'],
            ['name' => 'Frost Shaman',           'description' => 'Battlecry: Freeze an enemy minion.',                                                 'mana_cost' => 4,  'attack' => 3,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'Ice in the veins.'],
            ['name' => 'Elemental Amalgam',      'description' => 'Taunt. Battlecry: Gain the power of a random element.',                              'mana_cost' => 4,  'attack' => 3,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'shaman', 'flavor_text' => 'Fire. Frost. Earth. Wind. All at once.'],
            ['name' => 'Thunder Caller',         'description' => 'Battlecry: Summon a 3/2 Lightning Elemental.',                                       'mana_cost' => 5,  'attack' => 4,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'shaman', 'flavor_text' => 'He never calls alone.'],
            ['name' => 'Ancestral Spirit',       'description' => 'Deathrattle: Return this minion to life with +1/+1.',                                'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'shaman', 'flavor_text' => 'The ancestors answer.'],
            ['name' => 'Magma Golem',            'description' => 'At end of your turn, deal 2 damage to the enemy hero.',                              'mana_cost' => 5,  'attack' => 5,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'shaman', 'flavor_text' => 'Slow. Inevitable. Burning.'],
            ['name' => 'Tide Turner',            'description' => 'Battlecry: Draw 2 cards. Overload (2).',                                             'mana_cost' => 3,  'attack' => 3,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'shaman', 'flavor_text' => 'Power has its price.'],
            ['name' => 'Storm Giant',            'description' => 'Costs 1 less for each Mana you have overloaded this game.',                          'mana_cost' => 7,  'attack' => 7,    'health' => 7,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'shaman', 'flavor_text' => 'Overload fuels the giant.'],
            ['name' => 'Volcano Spirit',         'description' => 'Battlecry: Deal 3 damage to all enemies.',                                           'mana_cost' => 6,  'attack' => 5,    'health' => 6,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'shaman', 'flavor_text' => 'Its arrival is never quiet.'],
            ['name' => 'Ancient Elementalist',   'description' => 'Battlecry: Summon a 2/2 Totem of each element.',                                     'mana_cost' => 5,  'attack' => 4,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'shaman', 'flavor_text' => 'Four elements. One master.'],
            ['name' => 'Windlord Vael',          'description' => 'Windfury, Taunt, Rush. Battlecry: Summon a 5/5 Lightning Giant.',                    'mana_cost' => 8,  'attack' => 3,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'legendary', 'hero_class' => 'shaman', 'flavor_text' => 'The last of the Windlords.'],
            ['name' => 'Frost Shock',            'description' => 'Deal 1 damage to a minion and Freeze it.',                                           'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'Cold and sharp.'],
            ['name' => 'Lightning Bolt',         'description' => 'Deal 3 damage. Overload (1).',                                                       'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'The sky has opinions.'],
            ['name' => 'Chain Lightning',        'description' => 'Deal 3 damage. Summon a 1/1 Spark for each enemy hit.',                              'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'One bolt, many lessons.'],
            ['name' => 'Healing Rain',           'description' => 'Restore 3 Health to all friendly characters.',                                       'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'The land provides.'],
            ['name' => 'Rockbiter Weapon',       'description' => 'Give a minion +3 Attack this turn.',                                                 'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'Stone knows how to bite.'],
            ['name' => 'Hex',                    'description' => 'Transform a minion into a 0/1 Frog with Taunt.',                                     'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'shaman', 'flavor_text' => 'A fitting end.'],
            ['name' => 'Earthquake',             'description' => 'Deal 3 damage to all minions.',                                                      'mana_cost' => 5,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'shaman', 'flavor_text' => 'The ground decides.'],
            ['name' => 'Call of the Elements',   'description' => 'Discover a random Elemental minion.',                                                'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'shaman', 'flavor_text' => 'The elements always answer.'],
            ['name' => 'Elemental Surge',        'description' => 'Deal 2 damage to all enemies. Summon 2 random Elementals.',                          'mana_cost' => 6,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'shaman', 'flavor_text' => 'Controlled chaos.'],
            ['name' => 'Ancestral Recall',       'description' => 'Return a friendly minion to your hand. Summon a copy of it.',                        'mana_cost' => 5,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'shaman', 'flavor_text' => 'The spirits remember.'],
            ['name' => 'Maelstrom',              'description' => 'Deal 3 damage to all minions and the enemy hero. Overload (3).',                     'mana_cost' => 9,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'legendary', 'hero_class' => 'shaman', 'flavor_text' => 'The vortex consumes all.'],
            ['name' => 'Doomhammer',             'description' => 'Windfury. Overload (2).',                                                            'mana_cost' => 5,  'attack' => 2,    'health' => 8,    'card_type' => 'weapon', 'rarity' => 'epic',      'hero_class' => 'shaman', 'flavor_text' => 'It sings in the storm.'],
            ['name' => 'Flint and Steel',        'description' => 'After attacking, deal 1 damage to all enemies.',                                     'mana_cost' => 2,  'attack' => 2,    'health' => 2,    'card_type' => 'weapon', 'rarity' => 'common',    'hero_class' => 'shaman', 'flavor_text' => 'A spark is all it takes.'],
            ['name' => 'Stormforged Axe',        'description' => 'Battlecry: Deal 3 damage to a minion. Overload (1).',                                'mana_cost' => 4,  'attack' => 3,    'health' => 3,    'card_type' => 'weapon', 'rarity' => 'rare',      'hero_class' => 'shaman', 'flavor_text' => 'Tempered by lightning.'],

            // ===== ROGUE =====
            ['name' => 'Street Thug',            'description' => 'Combo: Gain +1/+1.',                                                                 'mana_cost' => 1,  'attack' => 1,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'Small, scrappy, and dangerous.'],
            ['name' => 'Cutpurse',               'description' => 'Whenever this damages the enemy hero, add a Coin to your hand.',                     'mana_cost' => 2,  'attack' => 2,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'Quicker than the eye.'],
            ['name' => 'Smoke Stalker',          'description' => 'Stealth.',                                                                            'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'Where there is smoke, there is an edge.'],
            ['name' => 'Backstabber',            'description' => 'Can only attack minions that have not attacked yet.',                                 'mana_cost' => 3,  'attack' => 3,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'The unprepared are the safest targets.'],
            ['name' => 'Shadow Rogue',           'description' => 'Stealth. Rush.',                                                                     'mana_cost' => 4,  'attack' => 4,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'Seen only after the deed is done.'],
            ['name' => 'Vanishing Act',          'description' => 'Battlecry: Add a random Rogue card to your hand.',                                   'mana_cost' => 2,  'attack' => 1,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'Now you see her...'],
            ['name' => 'Poisonblade Imp',        'description' => 'Poisonous.',                                                                         'mana_cost' => 2,  'attack' => 3,    'health' => 1,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'The smallest wounds are the deadliest.'],
            ['name' => 'Master Thief',           'description' => 'Battlecry: Take a random card from your opponent\'s hand.',                          'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'rogue', 'flavor_text' => 'What\'s yours is mine.'],
            ['name' => 'Shadow Dancer',          'description' => 'Stealth. Deathrattle: Deal 3 damage to a random enemy.',                             'mana_cost' => 4,  'attack' => 4,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'rogue', 'flavor_text' => 'Even in death, she strikes.'],
            ['name' => 'Viper Agent',            'description' => 'Battlecry: Destroy a minion with 3 or less Health.',                                 'mana_cost' => 5,  'attack' => 4,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'rogue', 'flavor_text' => 'Quick, clean, professional.'],
            ['name' => 'Goblin Safecracker',     'description' => 'Battlecry: Add 2 Coins to your hand.',                                              'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'rogue', 'flavor_text' => 'No lock it cannot crack.'],
            ['name' => 'Shadow Mimic',           'description' => 'Battlecry: Create a copy of a minion in your opponent\'s hand.',                     'mana_cost' => 4,  'attack' => 3,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'rogue', 'flavor_text' => 'Imitation is the sincerest form of theft.'],
            ['name' => 'Shadow Assassin',        'description' => 'Stealth. Battlecry: Deal 5 damage divided among enemies.',                           'mana_cost' => 6,  'attack' => 5,    'health' => 6,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'rogue', 'flavor_text' => 'One contract. Many casualties.'],
            ['name' => 'Shadowstep Master',      'description' => 'Battlecry: Return a friendly minion to your hand. It costs (2) less.',               'mana_cost' => 5,  'attack' => 4,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'rogue', 'flavor_text' => 'A step ahead, always.'],
            ['name' => 'Plague Knife Wielder',   'description' => 'Poisonous. Combo: Your hero gains Poisonous this turn.',                             'mana_cost' => 5,  'attack' => 5,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'rogue', 'flavor_text' => 'Even a scratch is fatal.'],
            ['name' => 'Valeera Shadowborn',     'description' => 'Stealth. Battlecry: All your Rogue cards now have Combo.',                           'mana_cost' => 7,  'attack' => 5,    'health' => 6,    'card_type' => 'minion', 'rarity' => 'legendary', 'hero_class' => 'rogue', 'flavor_text' => 'She turned the guild into a legend.'],
            ['name' => 'Backstab',               'description' => 'Deal 2 damage to an undamaged minion.',                                              'mana_cost' => 0,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'From behind. Always.'],
            ['name' => 'Eviscerate',             'description' => 'Deal 2 damage. Combo: Deal 4 damage instead.',                                       'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'Twice as nasty with a running start.'],
            ['name' => 'Preparation',            'description' => 'The next spell you cast this turn costs (2) less.',                                  'mana_cost' => 0,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'Ready before the mark even knows.'],
            ['name' => 'Fan of Knives',          'description' => 'Deal 1 damage to all enemy minions. Draw a card.',                                   'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'Spread the wealth.'],
            ['name' => 'Poisoned Blades',        'description' => 'Give your weapon +1 Attack for each card in your hand.',                             'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'Knowledge coats the blade.'],
            ['name' => 'Shadowstep',             'description' => 'Return a friendly minion to your hand. It costs (2) less.',                          'mana_cost' => 0,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'rogue', 'flavor_text' => 'Here and gone.'],
            ['name' => 'Blade Flurry',           'description' => 'Destroy your weapon. Deal its Attack value to all enemies.',                         'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'rogue', 'flavor_text' => 'Go out in style.'],
            ['name' => 'Sprint',                 'description' => 'Draw 4 cards.',                                                                      'mana_cost' => 7,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'rogue', 'flavor_text' => 'The best escape is information.'],
            ['name' => 'Shadow Dance',           'description' => 'Create a copy of each friendly minion with Stealth.',                                'mana_cost' => 5,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'rogue', 'flavor_text' => 'Shadows multiply.'],
            ['name' => 'Assassination',          'description' => 'Destroy an enemy minion.',                                                           'mana_cost' => 5,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'rogue', 'flavor_text' => 'Clean. Professional. Final.'],
            ['name' => 'Marked for Death',       'description' => 'Destroy all enemy minions. They cannot be resurrected this game.',                   'mana_cost' => 8,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'legendary', 'hero_class' => 'rogue', 'flavor_text' => 'The contract is absolute.'],
            ['name' => 'Wicked Knife',           'description' => 'Combo: Gain +1 Attack.',                                                             'mana_cost' => 1,  'attack' => 1,    'health' => 2,    'card_type' => 'weapon', 'rarity' => 'common',    'hero_class' => 'rogue', 'flavor_text' => 'Unassuming. Deadly.'],
            ["name" => "Perdition's Blade",      'description' => 'Battlecry: Deal 1 damage. Combo: Deal 4 damage instead.',                            'mana_cost' => 3,  'attack' => 2,    'health' => 2,    'card_type' => 'weapon', 'rarity' => 'rare',      'hero_class' => 'rogue', 'flavor_text' => 'Condemned by its own edge.'],
            ["name" => "Assassin's Edge",        'description' => 'After your hero attacks, deal 1 damage to all enemies.',                             'mana_cost' => 5,  'attack' => 3,    'health' => 4,    'card_type' => 'weapon', 'rarity' => 'epic',      'hero_class' => 'rogue', 'flavor_text' => 'Leaves a lasting impression.'],

            // ===== PRIEST =====
            ['name' => 'Acolyte of Ember',       'description' => 'Battlecry: Restore 2 Health to your hero.',                                          'mana_cost' => 1,  'attack' => 1,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'Faithful to the last ember.'],
            ['name' => 'Holy Novice',            'description' => 'Battlecry: Give a friendly minion +0/+2.',                                           'mana_cost' => 2,  'attack' => 1,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'Her prayers add substance.'],
            ["name" => "Light's Sworn",          'description' => 'Whenever you restore Health, gain +1/+0.',                                           'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'Bound to serve the light.'],
            ['name' => 'Praying Monk',           'description' => 'At end of your turn, restore 1 Health to your hero.',                                'mana_cost' => 2,  'attack' => 1,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'Unceasing in devotion.'],
            ['name' => 'Temple Guard',           'description' => 'Taunt. Battlecry: Restore 3 Health to a character.',                                 'mana_cost' => 4,  'attack' => 3,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'The temple shall not fall.'],
            ['name' => 'Choir Singer',           'description' => 'Battlecry: Give all friendly minions +0/+1.',                                        'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'Her song strengthens all who hear it.'],
            ['name' => 'Faithful Shepherd',      'description' => 'Whenever you cast a spell, restore 2 Health to a random friendly character.',         'mana_cost' => 4,  'attack' => 3,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'No flock is left behind.'],
            ['name' => 'Holy Champion',          'description' => 'Whenever you restore Health, gain +2/+0.',                                           'mana_cost' => 4,  'attack' => 3,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'priest', 'flavor_text' => 'Healing fuels the fight.'],
            ['name' => 'Lightwell',              'description' => 'At the start of your turn, restore 3 Health to your most wounded ally.',              'mana_cost' => 2,  'attack' => 0,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'priest', 'flavor_text' => 'It asks nothing, gives everything.'],
            ['name' => 'Mind Controller',        'description' => 'Battlecry: If your opponent has 4 or more minions, steal one at random.',             'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'priest', 'flavor_text' => 'Their thoughts, rearranged.'],
            ['name' => 'Temple Healer',          'description' => 'Battlecry: Restore 5 Health to a character.',                                        'mana_cost' => 5,  'attack' => 3,    'health' => 6,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'priest', 'flavor_text' => 'There is always more to give.'],
            ['name' => 'Inner Fire',             'description' => 'Battlecry: Set a friendly minion\'s Attack equal to its Health.',                    'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'priest', 'flavor_text' => 'The flame within ignites.'],
            ['name' => 'Resurrector',            'description' => 'Battlecry: Return a random friendly minion that died this game.',                     'mana_cost' => 5,  'attack' => 3,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'priest', 'flavor_text' => 'Life is not finished yet.'],
            ['name' => 'Voice of the Light',     'description' => 'Your healing spells also deal their value as damage to the enemy hero.',              'mana_cost' => 6,  'attack' => 4,    'health' => 6,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'priest', 'flavor_text' => 'Light heals and harms in equal measure.'],
            ['name' => 'Seraph of Dawn',         'description' => 'Divine Shield. Battlecry: Restore 7 Health to all friendly characters.',              'mana_cost' => 7,  'attack' => 5,    'health' => 7,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'priest', 'flavor_text' => 'Dawn brings renewal.'],
            ['name' => 'Lightbringer Solan',     'description' => 'Divine Shield. Battlecry: Fully restore all friendly characters to full Health.',     'mana_cost' => 8,  'attack' => 6,    'health' => 8,    'card_type' => 'minion', 'rarity' => 'legendary', 'hero_class' => 'priest', 'flavor_text' => 'The light of a thousand suns.'],
            ['name' => 'Lesser Heal',            'description' => 'Restore 2 Health to any character.',                                                  'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'Even small mercies matter.'],
            ['name' => 'Mind Blast',             'description' => 'Deal 5 damage to the enemy hero.',                                                   'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'The light can smite.'],
            ['name' => 'Holy Nova',              'description' => 'Deal 2 damage to all enemies. Restore 2 Health to all friendly characters.',          'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'A pulse of holy energy.'],
            ['name' => 'Power Word Shield',      'description' => 'Give a minion +0/+2. Draw a card.',                                                  'mana_cost' => 0,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'Protection costs nothing.'],
            ['name' => 'Dispel',                 'description' => 'Silence a minion.',                                                                   'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'Reduced to nothing.'],
            ['name' => 'Shadow Word Pain',       'description' => 'Destroy a minion with 3 or less Attack.',                                            'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'priest', 'flavor_text' => 'Small sins carry great weight.'],
            ['name' => 'Shadow Word Death',      'description' => 'Destroy a minion with 5 or more Attack.',                                            'mana_cost' => 5,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'priest', 'flavor_text' => 'The strong are not immune.'],
            ['name' => 'Circle of Healing',      'description' => 'Restore 4 Health to all minions.',                                                   'mana_cost' => 0,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'priest', 'flavor_text' => 'The circle closes. All are mended.'],
            ['name' => 'Mass Resurrection',      'description' => 'Summon 3 friendly minions that died this game.',                                      'mana_cost' => 7,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'priest', 'flavor_text' => 'They answer the call of the faithful.'],
            ['name' => 'Holy Fire',              'description' => 'Deal 5 damage to a minion. Restore 5 Health to your hero.',                          'mana_cost' => 6,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'priest', 'flavor_text' => 'The sacred flames both burn and mend.'],
            ['name' => 'Lightbomb',              'description' => 'Deal damage to each minion equal to its Attack.',                                     'mana_cost' => 6,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'legendary', 'hero_class' => 'priest', 'flavor_text' => 'The guilty condemn themselves.'],
            ['name' => 'Holy Mace',              'description' => 'After attacking, restore 2 Health to your hero.',                                    'mana_cost' => 3,  'attack' => 2,    'health' => 4,    'card_type' => 'weapon', 'rarity' => 'common',    'hero_class' => 'priest', 'flavor_text' => 'Strike and be made whole.'],
            ['name' => 'Staff of Light',         'description' => 'Your spells cost (1) less.',                                                         'mana_cost' => 4,  'attack' => 2,    'health' => 4,    'card_type' => 'weapon', 'rarity' => 'rare',      'hero_class' => 'priest', 'flavor_text' => 'Every prayer is amplified.'],
            ['name' => 'Benediction Scepter',    'description' => 'Overkill: Restore 5 Health to all friendly characters.',                             'mana_cost' => 5,  'attack' => 3,    'health' => 3,    'card_type' => 'weapon', 'rarity' => 'epic',      'hero_class' => 'priest', 'flavor_text' => 'Righteous destruction brings healing.'],

            // ===== WARLOCK =====
            ['name' => 'Imp Familiar',           'description' => 'Battlecry: Deal 1 damage to your hero. Draw a card.',                                'mana_cost' => 1,  'attack' => 1,    'health' => 1,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'Costly company.'],
            ['name' => 'Voidwalker',             'description' => 'Taunt.',                                                                             'mana_cost' => 1,  'attack' => 1,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'It walked out of the void. It would like to walk back in.'],
            ['name' => 'Fel Imp',                'description' => 'Battlecry: Discard a random card.',                                                  'mana_cost' => 2,  'attack' => 3,    'health' => 1,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'Chaos first, questions never.'],
            ['name' => 'Dread Infernal',         'description' => 'Battlecry: Deal 1 damage to all characters.',                                        'mana_cost' => 3,  'attack' => 3,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'It burns everything. Including you.'],
            ['name' => 'Darkshire Cultist',      'description' => 'Battlecry: Give a random Demon in your hand +1/+1.',                                 'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'They believe in something. It believes in them.'],
            ['name' => 'Felfire Hound',          'description' => 'Rush.',                                                                              'mana_cost' => 2,  'attack' => 2,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'Hungry for everything.'],
            ['name' => 'Doom Guard',             'description' => 'Rush. Battlecry: Discard 2 random cards.',                                          'mana_cost' => 5,  'attack' => 5,    'health' => 7,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'It costs more than you think.'],
            ['name' => 'Felguard',               'description' => 'Taunt. Battlecry: Destroy one of your Mana Crystals.',                               'mana_cost' => 3,  'attack' => 3,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'warlock', 'flavor_text' => 'A bargain with strings attached.'],
            ['name' => 'Void Caller',            'description' => 'Deathrattle: Summon a random Demon from your hand.',                                 'mana_cost' => 4,  'attack' => 3,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'warlock', 'flavor_text' => 'Its last act is a summons.'],
            ['name' => 'Abyssal Enforcer',       'description' => 'Battlecry: Deal 3 damage to all other characters.',                                  'mana_cost' => 6,  'attack' => 6,    'health' => 6,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'warlock', 'flavor_text' => 'Impartial. Merciless.'],
            ['name' => 'Soul Shardling',         'description' => 'Costs 1 less for each card you have discarded this game.',                           'mana_cost' => 4,  'attack' => 3,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'warlock', 'flavor_text' => 'Every lost card feeds it.'],
            ['name' => 'Twisted Vizier',         'description' => 'Battlecry: Gain 2 Health for each card in your hand.',                               'mana_cost' => 4,  'attack' => 3,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'warlock', 'flavor_text' => 'Knowledge is armour.'],
            ['name' => 'Chaos Demon',            'description' => 'Rush. Battlecry: Discard your hand. Draw 3 cards.',                                  'mana_cost' => 7,  'attack' => 6,    'health' => 8,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'warlock', 'flavor_text' => 'Out with the old.'],
            ['name' => 'Void Titan',             'description' => 'Taunt. Battlecry: Deal damage equal to your hand size to all enemies.',               'mana_cost' => 6,  'attack' => 6,    'health' => 6,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'warlock', 'flavor_text' => 'Every card you hold is a weapon.'],
            ['name' => 'Infernal Colossus',      'description' => 'Taunt. At end of your turn, deal 3 damage to your hero and all enemies.',             'mana_cost' => 8,  'attack' => 7,    'health' => 9,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'warlock', 'flavor_text' => 'Power unchecked consumes all.'],
            ["name" => "Gul'dan the Cursed",     'description' => 'Battlecry: Fill your hand with Demons from your deck.',                              'mana_cost' => 8,  'attack' => 5,    'health' => 9,    'card_type' => 'minion', 'rarity' => 'legendary', 'hero_class' => 'warlock', 'flavor_text' => 'The pact was always worth it.'],
            ['name' => 'Corruption',             'description' => 'Choose an enemy minion. At the start of your turn, destroy it.',                      'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'Patience. Everything rots eventually.'],
            ['name' => 'Shadow Bolt',            'description' => 'Deal 4 damage to a minion.',                                                         'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'A fistful of darkness.'],
            ['name' => 'Drain Soul',             'description' => 'Deal 2 damage to a minion. Restore 2 Health to your hero.',                          'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'Take what you need.'],
            ['name' => 'Siphon Soul',            'description' => 'Destroy a minion. Restore 3 Health to your hero.',                                   'mana_cost' => 6,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'A soul is a fine currency.'],
            ['name' => 'Hellfire',               'description' => 'Deal 3 damage to all characters.',                                                   'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'The demon cares not who burns.'],
            ['name' => 'Darkbomb',               'description' => 'Deal 3 damage.',                                                                     'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'warlock', 'flavor_text' => 'Compact destruction.'],
            ['name' => 'Soul Shatter',           'description' => 'Deal 5 damage to a minion. Discard a random card.',                                  'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'warlock', 'flavor_text' => 'Power always has a price.'],
            ['name' => 'Blood Pact',             'description' => 'Draw 3 cards. Deal 3 damage to your hero for each.',                                 'mana_cost' => 5,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'warlock', 'flavor_text' => 'The ink dries red.'],
            ['name' => 'Twisting Nether',        'description' => 'Destroy all minions.',                                                               'mana_cost' => 8,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'warlock', 'flavor_text' => 'Nothing survives the nether.'],
            ['name' => 'Cataclysm',              'description' => 'Destroy all minions with 3 or less Health. Discard a random card.',                  'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'warlock', 'flavor_text' => 'Some things must be purged.'],
            ['name' => 'Chaos Bolt',             'description' => 'Deal 4 damage to a random enemy four times.',                                        'mana_cost' => 6,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'legendary', 'hero_class' => 'warlock', 'flavor_text' => 'Chaos finds its own mark.'],
            ['name' => 'Cursed Blade',           'description' => 'While equipped, all damage your hero takes is doubled.',                              'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'weapon', 'rarity' => 'common',    'hero_class' => 'warlock', 'flavor_text' => 'Risk amplified.'],
            ['name' => 'Fel Reaver Claw',        'description' => 'After attacking, discard a random card.',                                            'mana_cost' => 4,  'attack' => 4,    'health' => 2,    'card_type' => 'weapon', 'rarity' => 'rare',      'hero_class' => 'warlock', 'flavor_text' => 'It costs more than durability.'],
            ['name' => 'Demonbane Edge',         'description' => 'Overkill: Summon a 3/3 Demon.',                                                     'mana_cost' => 5,  'attack' => 3,    'health' => 4,    'card_type' => 'weapon', 'rarity' => 'epic',      'hero_class' => 'warlock', 'flavor_text' => 'Excess energy summons servants.'],

            // ===== WARRIOR (additional) =====
            ['name' => 'Bloodied Berserker',     'description' => 'Whenever this minion takes damage, gain +2/+0.',                                     'mana_cost' => 2,  'attack' => 2,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'warrior', 'flavor_text' => 'Pain is fuel.'],
            ['name' => 'Gnomish Inventor',       'description' => 'Battlecry: Draw a card.',                                                            'mana_cost' => 4,  'attack' => 2,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'warrior', 'flavor_text' => 'Tiny hands, useful mind.'],
            ['name' => 'Enraged Troll',          'description' => 'Whenever this minion takes damage, gain +2/+0 and Rush.',                            'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'warrior', 'flavor_text' => 'Hurt it. See what happens.'],
            ['name' => 'Axe Grinder',            'description' => 'Battlecry: Equip a 2/2 Axe.',                                                       'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'warrior', 'flavor_text' => 'Always ready.'],
            ['name' => 'Battle Veteran',         'description' => 'Battlecry: Gain 3 Armor for each weapon you have played.',                           'mana_cost' => 4,  'attack' => 3,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'warrior', 'flavor_text' => 'Every scar is a trophy.'],
            ['name' => 'War Machine',            'description' => 'Taunt. Battlecry: Give all friendly minions +1/+0.',                                 'mana_cost' => 6,  'attack' => 6,    'health' => 7,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'warrior', 'flavor_text' => 'A juggernaut with allies.'],
            ['name' => 'Shield Slam',            'description' => 'Deal 1 damage to a minion for each Armor you have.',                                 'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'warrior', 'flavor_text' => 'The shield is a weapon too.'],
            ['name' => 'Slam',                   'description' => 'Deal 2 damage to a minion. If it survives, draw a card.',                            'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'warrior', 'flavor_text' => 'Not every hit is meant to kill.'],
            ['name' => 'Armorbreak',             'description' => 'Gain 2 Armor for each friendly minion. Deal 2 damage to all enemies.',               'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'warrior', 'flavor_text' => 'Protect and devastate.'],
            ['name' => 'Gorehowl',               'description' => 'Attacking a minion costs 1 Attack instead of 1 Durability.',                         'mana_cost' => 7,  'attack' => 7,    'health' => 1,    'card_type' => 'weapon', 'rarity' => 'legendary', 'hero_class' => 'warrior', 'flavor_text' => 'It weeps blood for those it slays.'],

            // ===== MAGE (additional) =====
            ['name' => 'Mana Wyrm',              'description' => 'Whenever you cast a spell, gain +1/+0.',                                             'mana_cost' => 1,  'attack' => 1,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'mage', 'flavor_text' => 'It feeds on raw magic.'],
            ["name" => "Sorcerer's Apprentice",  'description' => 'Your spells cost (1) less.',                                                         'mana_cost' => 2,  'attack' => 3,    'health' => 2,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'mage', 'flavor_text' => 'She makes every spell cheaper.'],
            ['name' => 'Icicle Golem',           'description' => 'Frozen minions take double damage from your spells.',                                'mana_cost' => 5,  'attack' => 4,    'health' => 6,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'mage', 'flavor_text' => 'Cold and calculating.'],
            ["name" => "Kael's Apprentice",      'description' => 'Every third spell you cast each turn is free.',                                      'mana_cost' => 4,  'attack' => 3,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'mage', 'flavor_text' => 'Three is the magic number.'],
            ['name' => 'Frostbolt',              'description' => 'Deal 3 damage to a character and Freeze it.',                                        'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'mage', 'flavor_text' => 'Cold, then cold again.'],
            ['name' => 'Arcane Intellect',       'description' => 'Draw 2 cards.',                                                                      'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'mage', 'flavor_text' => 'Knowledge is the greatest spell.'],
            ['name' => 'Mirror Image',           'description' => 'Summon two 0/2 Mirror Images with Taunt.',                                           'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'mage', 'flavor_text' => 'Which one is real? Neither.'],
            ['name' => "Conjurer's Calling",     'description' => 'Destroy a friendly minion. Summon 2 minions of the same cost.',                      'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'mage', 'flavor_text' => 'Something for something.'],
            ['name' => 'Elemental Evocation',    'description' => 'The next Elemental you play this turn costs (2) less.',                               'mana_cost' => 0,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'mage', 'flavor_text' => 'Discount conjuration.'],
            ['name' => 'Flamestrike',            'description' => 'Deal 4 damage to all enemy minions.',                                                'mana_cost' => 7,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'epic',      'hero_class' => 'mage', 'flavor_text' => 'No minion is safe.'],

            // ===== RANGER (additional) =====
            ['name' => 'Lone Wolf',              'description' => 'Has +2/+0 if you have no other minions.',                                            'mana_cost' => 3,  'attack' => 2,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'ranger', 'flavor_text' => 'Alone is how it likes it.'],
            ['name' => 'Pack Leader',            'description' => 'Whenever you summon a Beast, give it +2/+0.',                                        'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'ranger', 'flavor_text' => 'A pack that follows greatness.'],
            ['name' => 'Jungle Stalker',         'description' => 'Stealth. Battlecry: Summon a 2/2 Spider.',                                           'mana_cost' => 4,  'attack' => 4,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'ranger', 'flavor_text' => 'The jungle hides its hunters well.'],
            ['name' => 'Savannah Highmane',      'description' => 'Deathrattle: Summon two 2/2 Hyenas.',                                                'mana_cost' => 6,  'attack' => 6,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'ranger', 'flavor_text' => 'Even in death, it brings the pack.'],
            ['name' => 'Freezing Arrow',         'description' => 'Deal 2 damage to a minion and Freeze it.',                                           'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'ranger', 'flavor_text' => 'Stop them cold.'],
            ['name' => 'Bestial Wrath',          'description' => 'Give a Beast +2/+0 and Immune this turn.',                                           'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'ranger', 'flavor_text' => 'Unleash the wild.'],
            ['name' => 'Animal Companion',       'description' => 'Summon a random powerful Beast companion.',                                          'mana_cost' => 3,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'ranger', 'flavor_text' => 'The forest sends its champion.'],
            ['name' => 'Explosive Trap',         'description' => 'Secret: When your hero is attacked, deal 2 damage to all enemies.',                  'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'ranger', 'flavor_text' => 'Step lightly.'],
            ['name' => 'Dire Frenzy',            'description' => 'Give a Beast +3/+3. Shuffle 3 copies of it into your deck.',                         'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'ranger', 'flavor_text' => 'One becomes many.'],
            ['name' => 'Eaglehorn Bow',          'description' => 'Whenever a Secret is revealed, gain +1 Durability.',                                 'mana_cost' => 3,  'attack' => 3,    'health' => 2,    'card_type' => 'weapon', 'rarity' => 'rare',      'hero_class' => 'ranger', 'flavor_text' => 'Secrets sharpen its edge.'],

            // ===== PALADIN (additional) =====
            ['name' => 'Righteous Protector',    'description' => 'Taunt. Divine Shield.',                                                              'mana_cost' => 1,  'attack' => 1,    'health' => 1,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'paladin', 'flavor_text' => 'Small in stature, immovable in faith.'],
            ['name' => 'Silver Hand Sergeant',   'description' => 'Battlecry: Summon a 1/1 Silver Hand Recruit.',                                       'mana_cost' => 2,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'paladin', 'flavor_text' => 'Rank has privileges.'],
            ['name' => 'Aldor Peacekeeper',      'description' => 'Battlecry: Change an enemy minion\'s Attack to 1.',                                  'mana_cost' => 3,  'attack' => 3,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'paladin', 'flavor_text' => 'Peace. By force if necessary.'],
            ['name' => 'Sunwalker',              'description' => 'Taunt. Divine Shield.',                                                              'mana_cost' => 6,  'attack' => 4,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'paladin', 'flavor_text' => 'Walks in the light always.'],
            ['name' => 'Tirion\'s Squire',       'description' => 'Battlecry: Equip a 4/2 Holy Blade.',                                                'mana_cost' => 3,  'attack' => 2,    'health' => 3,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'paladin', 'flavor_text' => 'Carries the champion\'s legacy.'],
            ['name' => 'Argent Squadron',        'description' => 'Divine Shield. Battlecry: Give all friendly minions +1 Health.',                     'mana_cost' => 5,  'attack' => 4,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'paladin', 'flavor_text' => 'The squadron endures.'],
            ['name' => 'Guardian of Kings',      'description' => 'Battlecry: Restore 6 Health to your hero.',                                          'mana_cost' => 7,  'attack' => 5,    'health' => 6,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'paladin', 'flavor_text' => 'The king is safe while I stand.'],
            ['name' => 'Blessing of Kings',      'description' => 'Give a minion +4/+4.',                                                               'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'paladin', 'flavor_text' => 'Fit for royalty.'],
            ['name' => 'Consecration',           'description' => 'Deal 2 damage to all enemies.',                                                      'mana_cost' => 4,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'paladin', 'flavor_text' => 'Holy ground burns the wicked.'],
            ["name" => "Light's Justice",        'description' => 'After your hero attacks, restore 1 Health to all friendly minions.',                  'mana_cost' => 1,  'attack' => 1,    'health' => 4,    'card_type' => 'weapon', 'rarity' => 'common',    'hero_class' => 'paladin', 'flavor_text' => 'To strike is to heal.'],

            // ===== DRUID (additional) =====
            ['name' => 'Grove Tender',           'description' => 'Battlecry: Choose one — Give each player a Mana Crystal; or Draw a card.',           'mana_cost' => 3,  'attack' => 2,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'common',    'hero_class' => 'druid', 'flavor_text' => 'The grove provides.'],
            ['name' => 'Keeper of the Grove',    'description' => 'Battlecry: Choose one — Deal 2 damage; or Silence a minion.',                        'mana_cost' => 4,  'attack' => 2,    'health' => 4,    'card_type' => 'minion', 'rarity' => 'rare',      'hero_class' => 'druid', 'flavor_text' => 'Two powers. One keeper.'],
            ['name' => 'Ancient of War',         'description' => 'Choose one: Gain +5 Attack; or Gain +5 Health and Taunt.',                           'mana_cost' => 7,  'attack' => 5,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'druid', 'flavor_text' => 'War or defense. The ancient chooses.'],
            ['name' => 'Cenarius',               'description' => 'Choose one: Give your other minions +2/+2; or Summon two 2/5 Ancient Guardians.',    'mana_cost' => 9,  'attack' => 5,    'health' => 8,    'card_type' => 'minion', 'rarity' => 'legendary', 'hero_class' => 'druid', 'flavor_text' => 'Son of the Eternal One. The forest answers to him.'],
            ['name' => "Fandral's Seed",         'description' => 'While in play, your Choose One spells gain both effects.',                            'mana_cost' => 5,  'attack' => 4,    'health' => 5,    'card_type' => 'minion', 'rarity' => 'epic',      'hero_class' => 'druid', 'flavor_text' => 'Why choose one when you can have both?'],
            ['name' => 'Innervate',              'description' => 'Gain 2 Mana Crystals this turn only.',                                               'mana_cost' => 0,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'druid', 'flavor_text' => 'Nature lends. Nature takes back.'],
            ['name' => 'Wrath',                  'description' => 'Choose one: Deal 3 damage to a minion; or Deal 1 damage and draw a card.',            'mana_cost' => 2,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'druid', 'flavor_text' => 'The forest has feelings.'],
            ['name' => 'Nourish',                'description' => 'Choose one: Gain 2 Mana Crystals; or Draw 3 cards.',                                 'mana_cost' => 5,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'druid', 'flavor_text' => 'Resources or knowledge. Difficult choice.'],
            ['name' => 'Living Roots',           'description' => 'Choose one: Deal 2 damage; or Summon two 1/1 Saplings.',                             'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'common',    'hero_class' => 'druid', 'flavor_text' => 'The roots answer.'],
            ['name' => 'Naturalize',             'description' => 'Destroy a minion. Your opponent draws 2 cards.',                                     'mana_cost' => 1,  'attack' => null, 'health' => null, 'card_type' => 'spell',  'rarity' => 'rare',      'hero_class' => 'druid', 'flavor_text' => 'Returned to nature. At a cost.'],
        ];

        foreach ($cards as $cardData) {
            Card::updateOrCreate(['name' => $cardData['name']], $cardData);
        }
    }
}
